// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqjHLvkOkvSSJKe71Vo5YI2NQXtUnkX2s',
    appId: '1:881588133937:web:b26b2b67b1352ac4ae7510',
    messagingSenderId: '881588133937',
    projectId: 'messageapps-dbc91',
    authDomain: 'messageapps-dbc91.firebaseapp.com',
    storageBucket: 'messageapps-dbc91.firebasestorage.app',
    measurementId: 'G-MR2TSH231P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl2A1aBUkD48slMOPIAVM6NA1PUTCHsgE',
    appId: '1:881588133937:android:6aa750e8363737abae7510',
    messagingSenderId: '881588133937',
    projectId: 'messageapps-dbc91',
    storageBucket: 'messageapps-dbc91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK5Fe4LFZ2T1sbtx_tppQM8j8xc7bxVvQ',
    appId: '1:881588133937:ios:95e19411a7ec29e9ae7510',
    messagingSenderId: '881588133937',
    projectId: 'messageapps-dbc91',
    storageBucket: 'messageapps-dbc91.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK5Fe4LFZ2T1sbtx_tppQM8j8xc7bxVvQ',
    appId: '1:881588133937:ios:95e19411a7ec29e9ae7510',
    messagingSenderId: '881588133937',
    projectId: 'messageapps-dbc91',
    storageBucket: 'messageapps-dbc91.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqjHLvkOkvSSJKe71Vo5YI2NQXtUnkX2s',
    appId: '1:881588133937:web:2cf45a9ff1a924a5ae7510',
    messagingSenderId: '881588133937',
    projectId: 'messageapps-dbc91',
    authDomain: 'messageapps-dbc91.firebaseapp.com',
    storageBucket: 'messageapps-dbc91.firebasestorage.app',
    measurementId: 'G-HZ56D2B8JJ',
  );
}
